NYPL/engineering-general

standards/logging.md

So, I noticed that CloudWatch truncates log messages at 256 KB. This can cause message to have malformed JSON. This happened to me so I thought I should add some guidance here.

Added guidance about log message size limits

---

standards/naming-conventions.md

This PR adds the AWS Profile Names section under Naming Conventions and inserts the links that reference Monitoring & Alarms for AWS.
This addresses #31

Integrate aws profile names convention

---

README.md

I thought it might be helpful to add a "Documentation" section to the main README to link to documentation that is somewhat relevant across projects/applications. Maybe we can try this out and see if it becomes overwhelming. Thoughts?

Add documentation section to README

---

on-off-board/onboarding.md

Just adding a note about Data Warehouse DB credentials to the onboarding/offboarding section. 
Sending PR for visibility. Going to auto-merge.

Add data warehouse to onboarding

---

README.md
security/README.md
security/secrets.md

Hi all,
This is a draft of guidelines intended to used for **storing** and **sharing** secrets 🔑  more securely .
It relies on [AWS SSM Parameter Store](http://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) which may or may not be the best tool. As far as I know, Parameter Store generally has good feedback and there is a lot of tooling (e.g. [https://github.com/nak2k/node-ssm-params](https://github.com/nak2k/node-ssm-params)) as well as just the regular AWS SDK.
Hopefully this can kick off some good conversation... and help us stop sharing/storing secrets in Slack, email, Google docs, etc. 😉

Add Secret Management guidelines

---

on-off-board/onboarding.md

Hey @holingpoon & @capdeploy...
This adds Travis CI to our list of accounts and notes that Travis account management is controlled via Github team access.

Add Travis CI to our list of accounts.

---

standards/naming-conventions.md

Hey @thisisstephenbetts 
This documents the naming convention for SQS queues.
Let me know if you think there should be edits or additions.

Add documentation about SQS naming conventions

---

on-off-board/onboarding.md

We use MFA on AWS.
Shouldn't we note that?
Is this the best place for that?

Add notes indicating that we use MFA on AWS

---

standards/peer-review.md

The MyLibraryNYC team established some norms to increase predictability of PR review on the project, so I'm suggesting that other teams explicitly set their own norms for PR review too.

Project-specific norms for PR review

---

standards/travis-ci.md

Adds troubleshooting notes to our travis-ci documentation related to encryption failures arising from mismatches between *which* travis property actually runs builds and which travis endpoint one's local machine uses to encrypt values.

Document troubleshooting encryption failure due to endpoint mismatch

---

standards/travis-ci.md

The current link to get the travis encryption command results in a redirect (to the wrong page) and a message:
```
You have been redirected to the newer AWS Systems Manager console. By July 1, 2019, Systems Manager links in your EC2 console will be removed. Please update your bookmarks before that date.
```
This branch fixes the link as well as a typo.

Fix broken link

---

other/README.md
other/deprecating-apps.md
other/updating-header.md
standards/decommissioning.md

I wasn't sure where to write this so I created a new file for this under the `other` directory. Let me know if I'm missing something and should include it.
This is to cover two specific cases I recently encountered:
* I'm moving code from one codebase to another and will deprecate the original codebase.
* I received a PR for a codebase that is deprecated and I'm assuming the developer did not know that it's no longer being used.

Adding a note on deprecating apps and codebases.

---

README.md
post-mortems/sample.md
standards/root-cause-analysis.md
standards/technical-approach.md

This adds the creation of TADs to the engineering best practices documentation, as this is something that is being required for new work. It also updates the RCA documentation to be sure that the transition from post-mortems to RCA is currently in place and that post-mortems should not be created. It also removes a reference to a non-existent shared drive for RCAs.

NOREF Add TAD documentation and update RCA docs

---

README.md
standards/ci.md
standards/github-actions.md

This branch adds some documentation about configuring GitHub Actions to report test results to Slack. I started a new document for GitHub Actions since this is the first time we're really talking about them here, but there's clearly a lot more that could go into that document.

Document the integration between GitHub Actions and Slack 

---

README.md
on-off-board/github-org-management.md
on-off-board/offboarding.md
on-off-board/onboarding.md

Adds a new page with details about how we are managing the NYPL GitHub Organization
Details in this [project plan Google doc](https://docs.google.com/document/d/1_-fHwKp91d7-1zuYGucYrRUdOJ94QcfC6cGgIyy6oLQ/edit).

Add GitHub Org management best practices

---

other/updating-header.md

Old doc that needed an update. We no longer use the npm Header component and should point to the new repo.

Updated NYPL Header app doc

---

standards/technical-approach.md

After many conversations with engineers about length of the TAD drafting process I'd like to float a idealized version of the process here. This isn't intended to be prescriptive but to provide guidence on how someone _could_ move through the drafting process. Any and all feedback on this is more than welcome.
I've also made another change and shifted two situations from MUST to SHOULD for when a TAD is needed. These are the clauses for when work will be completed by multiple engineers or over mulitple sprints. While sometimes useful we are not regularly following this practice and it seems to be an uneccsary requirement.

TAD Timeline Update

---

standards/peer-review.md

This PR updates our page on PR review best practices. This page hasn't been touched in 5+ years so this includes both a general update as well as the addition of a few things:
- Added recommendation to use a `CODEOWNERS` file to help encourage a practice of tagging all team members in PRs
- Added general recommendation for timing and length of PR review processes
- Added recommendation to re-tag reviewers after updating a PR based on feedback to bump it back up in peoples' inboxes
- Generally reformatted
Please provide any feedback or additional best practices that you'd like to see added!

PR Review Best Practices

---

on-off-board/offboarding.md
on-off-board/onboarding.md

Our onboarding documentation was out of date and focused largely on adding people to accounts. This is misleading and neglects to mention the main goal of our _actual_ onboarding process: To welcome people to the team!
This rewrite attempts to center that more and update the account list to better reflect what is used and important in NYPL Digital (e.g. Less Jenkins, More GitHub)

Onboarding Re-Write

---

standards/technical-approach.md

- The shared TAD google drive link was broken
- This change fixes it!
- clicked on link!

fixing shared tad google drive link

---

standards/github-actions.md

This updates the Github Actions standards file to include script examples in Digital for running unit tests and deploying to AWS. This could use more examples from other projects so please feel free to let me know so I can add them.
Open questions:
- Not sure if the "Reporting results to Slack" section is still applicable.

Github Actions file update

---

standards/peer-review.md

Updated PR review guidelines based on the breakout discussion groups from the 06/11/2025 engineering meeting
[Link to Figjam board](https://www.figma.com/board/p8BeKLxqPrQva59IjdK7pv/Pull-Request--PR--Review-Process-Brainstorm?node-id=0-1&t=x0cRnKj6txvY2qDY-1)

Update peer review page based on drafted guidelines
